#ifndef N64_GAMES_H_
#define N64_GAMES_H_

//List of N64 Games
enum N64_ROM_ID
{
	UNKNOWN_ROM,
	_1080_SNOWBOARDING,
    BANJO_KAZOOIE,
    BANJO_TOOIE,
	BOMBERMAN_64,
	CONKERS_BAD_FUR_DAY,
	DIDDY_KONG_RACING,
	DONKEY_KONG_64,
	DR_MARIO,
	FIGHTERS_DESTINY,
	FIGHTER_DESTINY_2,
	F_ZERO_X,
	GOLDEN_EYE,
	LEGEND_OF_ZELDA_OCARINA_OF_TIME,
	MARIO_KART_64,
	PAPER_MARIO,
	PERFECT_DARK,
    SUPER_MARIO_64,
	SUPER_SMASH_BROS,
	STAR_FOX_64,	    
    SOUTH_PARK_RALLY,	
	WAVE_RACE_64,
	WORLD_DRIVER_CHAMPOINSHIP,
	YOSHIS_STORY,
};


#endif